name: build executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: make
      run: make -j2
    
    - uses: actions/upload-artifact@v4
      with:
        name: finalBin
        path: myProgram
        
